### ISSUE TITLE
Choose a licence for this project

### ISSUE THREAD

**Issue by MikeDimmickMnetics** [josundt/Durelia#1]
Hi,

I'm considering adopting Durelia for our single page application, which uses Durandal at present. We're hitting a real pain point with managing dependencies in our viewmodel unit tests; currently we're either using [Squire.js](https://github.com/iammerrick/Squire.js), or a form of 'bastard injection' where the constructor has optional parameters for its dependencies, and either uses the passed-in dependencies (as tests do) or requires them in if the parameters are `undefined` (as Durandal does not pass them in).

I'd like to adopt some form of IoC container, which would hook into Durandal and inject the dependencies appropriately when Durandal loads the viewmodel. It looks like Durelia would fit the bill.

What licence is this code available under?

**Comment by josundt** [comment]
I have added an MIT LICENCE.md file.
