### ISSUE TITLE
Not recognizing observable plugin

### ISSUE THREAD

**Issue by kakins** [josundt/Durelia#7]
I keep getting the error that it doesn't think I have the observable plugin enabled, however I do...

```
    app.configurePlugins({
        router: true,
        observable: {
            changeDetection: 'modelChanged'
        },
        dialog: true,
        widget: false,
        history: true
    });
```

**Comment by josundt** [comment]
I don't think I ever tested the observable plugin's _change detection_ feature, I only tested setting the `observable` property to true with Durelia.

Maybe comparing your code with the sample app in this repository could help...
